Update build-release.yml

diff --git a/.github/workflows/build-release.yml b/.github/workflows/build-release.yml
--- a/.github/workflows/build-release.yml
+++ b/.github/workflows/build-release.yml
@@ -19,7 +19,14 @@ jobs:
         with:
           java-version: '17'
           distribution: 'temurin'
-          cache: gradle
+
+      - name: Verificar disponibilidad de Gradlew
+        run: |
+          if [ ! -f ./gradlew ]; then
+            echo "Error: No se encuentra el archivo ./gradlew en la raíz."
+            ls -la
+            exit 1
+          fi
 
       - name: Dar permisos a Gradlew
         run: chmod +x gradlew
